"""
Script 1: Download and filter The Stack v2 C# slice
=====================================================
Prerequisites:
    pip install datasets huggingface_hub tqdm

Usage:
    # First, accept the dataset license at:
    # https://huggingface.co/datasets/bigcode/the-stack-v2
    # Then log in:
    huggingface-cli login

    python 01_stack_v2_csharp.py --output_dir ./data/stack_v2_csharp

The Stack v2 is gated — you must request access on HuggingFace first.
This script streams the dataset to avoid downloading the full 67TB archive.
It filters to C# files only, applies quality heuristics, and saves to JSONL.
"""

import argparse
import json
import re
from pathlib import Path

from datasets import load_dataset
from tqdm import tqdm


# ---------------------------------------------------------------------------
# Quality filter heuristics
# ---------------------------------------------------------------------------

MIN_CHARS = 200          # discard tiny snippets
MAX_CHARS = 50_000       # discard huge auto-generated files
MIN_LINES = 10
MAX_LINE_LENGTH = 500    # flag minified / auto-generated code
MAX_AVG_LINE_LENGTH = 150
MIN_ALPHANUM_RATIO = 0.4 # discard files that are mostly symbols/whitespace
MAX_COMMENT_RATIO = 0.7  # discard files that are mostly comments/docs

# Patterns that suggest auto-generated or low-quality files
AUTOGEN_PATTERNS = [
    r"<auto-generated\s*/?>",
    r"This code was generated by",
    r"Generated by .{0,60}on \d{4}",
    r"Do not edit this file",
    r"// <autogenerated>",
]
AUTOGEN_RE = re.compile("|".join(AUTOGEN_PATTERNS), re.IGNORECASE)

DESIGNER_SUFFIXES = (
    ".designer.cs",
    ".g.cs",
    ".g.i.cs",
    ".generated.cs",
    ".AssemblyInfo.cs",
)


def is_quality_file(example: dict) -> bool:
    content: str = example.get("content", "") or ""
    path: str = example.get("path", "") or ""

    # --- Path-based filters ---
    path_lower = path.lower()
    if any(path_lower.endswith(s) for s in DESIGNER_SUFFIXES):
        return False
    if "/obj/" in path_lower or "/bin/" in path_lower:
        return False

    # --- Size filters ---
    if len(content) < MIN_CHARS or len(content) > MAX_CHARS:
        return False

    lines = content.splitlines()
    if len(lines) < MIN_LINES:
        return False

    # --- Line length filters ---
    if max((len(l) for l in lines), default=0) > MAX_LINE_LENGTH:
        return False
    avg_line_len = sum(len(l) for l in lines) / max(len(lines), 1)
    if avg_line_len > MAX_AVG_LINE_LENGTH:
        return False

    # --- Alphanumeric ratio ---
    alphanum = sum(c.isalnum() for c in content)
    if alphanum / max(len(content), 1) < MIN_ALPHANUM_RATIO:
        return False

    # --- Comment ratio ---
    comment_lines = sum(
        1 for l in lines
        if l.strip().startswith("//") or l.strip().startswith("*")
    )
    if comment_lines / max(len(lines), 1) > MAX_COMMENT_RATIO:
        return False

    # --- Auto-generated detection ---
    # Only inspect the first 20 lines for performance
    header = "\n".join(lines[:20])
    if AUTOGEN_RE.search(header):
        return False

    return True


def extract_fields(example: dict) -> dict:
    """Retain only the fields we need downstream."""
    return {
        "content": example["content"],
        "path": example.get("path", ""),
        "repo_name": example.get("repo_name", ""),
        "license": example.get("license", ""),
        "size": example.get("size", 0),
        "source": "the-stack-v2",
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output_dir", default="./data/stack_v2_csharp")
    parser.add_argument("--max_samples", type=int, default=None,
                        help="Cap total samples (useful for testing)")
    parser.add_argument("--shard_size", type=int, default=50_000,
                        help="Records per output JSONL shard")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Loading The Stack v2 (C# subset, streaming)...")
    ds = load_dataset(
        "bigcode/the-stack-v2",
        "C#",
        split="train",
        streaming=True,
        trust_remote_code=True,
    )

    shard_idx = 0
    kept = 0
    seen = 0
    shard_records = []

    def flush_shard():
        nonlocal shard_idx
        shard_path = out_dir / f"shard_{shard_idx:04d}.jsonl"
        with open(shard_path, "w", encoding="utf-8") as f:
            for rec in shard_records:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        print(f"  Wrote shard {shard_idx} ({len(shard_records)} records) → {shard_path}")
        shard_idx += 1
        shard_records.clear()

    with tqdm(desc="Filtering", unit=" files") as pbar:
        for example in ds:
            seen += 1
            pbar.update(1)
            pbar.set_postfix(kept=kept, ratio=f"{kept/max(seen,1):.1%}")

            if not is_quality_file(example):
                continue

            shard_records.append(extract_fields(example))
            kept += 1

            if len(shard_records) >= args.shard_size:
                flush_shard()

            if args.max_samples and kept >= args.max_samples:
                break

    if shard_records:
        flush_shard()

    print(f"\nDone. Kept {kept:,} / {seen:,} files ({kept/max(seen,1):.1%} pass rate)")
    print(f"Output: {out_dir}")


if __name__ == "__main__":
    main()
