"""
Script 2: Targeted GitHub scraper for high-quality C# repos
=============================================================
Prerequisites:
    pip install PyGithub requests tqdm python-dotenv

Usage:
    export GITHUB_TOKEN=ghp_your_token_here   # needs repo:read scope
    python 02_github_scraper.py --output_dir ./data/github_csharp

This script:
  1. Searches for high-quality C# repos using quality signals beyond stars
  2. Clones only .cs files via the GitHub Contents API (no git clone needed)
  3. Filters files using the same heuristics as script 1, plus:
     - CI badge / workflow file presence
     - Modern C# version detection (C# 8+)
     - Test file inclusion (signals the repo has coverage)
  4. Saves to JSONL with rich metadata per file

Rate limits: GitHub REST API allows 5000 requests/hour with a token.
The script tracks and respects this automatically.
"""

import argparse
import json
import os
import re
import time
from pathlib import Path
from typing import Optional

import requests
from dotenv import load_dotenv
from github import Github, GithubException, RateLimitExceededException
from github.Auth import Token
from tqdm import tqdm

load_dotenv()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_SEARCH_QUERIES = [
    # Modern .NET / C# repos with real test coverage
    "language:csharp stars:>100 pushed:>2023-01-01 topic:dotnet",
    "language:csharp stars:>100 pushed:>2023-01-01 topic:csharp",
    "language:csharp stars:>200 pushed:>2023-01-01",
    # Domain-specific high quality signals
    "language:csharp stars:>50 topic:aspnetcore pushed:>2023-01-01",
    "language:csharp stars:>50 topic:blazor pushed:>2023-01-01",
    "language:csharp stars:>50 topic:unity pushed:>2023-01-01",
    "language:csharp stars:>50 topic:ef-core pushed:>2023-01-01",
]

MIN_STARS = 50
MAX_REPOS = 2000
MAX_FILES_PER_REPO = 200   # avoid over-indexing single large repos
MIN_CSHARP_RATIO = 0.3     # at least 30% of the repo should be C#

# Modern C# features that indicate the file isn't ancient legacy code
MODERN_CSHARP_PATTERNS = [
    r"\bnull\s*!",          # null-forgiving operator (C# 8+)
    r"\brecord\s+\w+",      # record types (C# 9+)
    r"\binit\s*;",          # init accessors (C# 9+)
    r"\bfile\s+class\b",    # file-scoped types (C# 11+)
    r"required\s+\w+\s+\w+\s*{",  # required members (C# 11+)
    r"<\w+>\s*\(",          # generic method calls
    r"=>\s*\{",             # expression bodies
    r"\bawait\b",           # async/await
    r"\.ToList\(\)|\.ToArray\(\)|\.Where\(|\.Select\(",  # LINQ
    r"ILogger|IConfiguration|IServiceCollection",       # DI patterns
]
MODERN_RE = re.compile("|".join(MODERN_CSHARP_PATTERNS))

# Re-use the quality filters from script 1
MIN_CHARS = 200
MAX_CHARS = 50_000
MIN_LINES = 10
MAX_LINE_LENGTH = 500
MAX_AVG_LINE_LENGTH = 150
MIN_ALPHANUM_RATIO = 0.4
MAX_COMMENT_RATIO = 0.7
DESIGNER_SUFFIXES = (".designer.cs", ".g.cs", ".g.i.cs", ".generated.cs")
AUTOGEN_RE = re.compile(
    r"<auto-generated|This code was generated|Do not edit this file|// <autogenerated>",
    re.IGNORECASE
)


def is_quality_content(content: str, path: str) -> bool:
    path_lower = path.lower()
    if any(path_lower.endswith(s) for s in DESIGNER_SUFFIXES):
        return False
    if "/obj/" in path_lower or "/bin/" in path_lower or "/migrations/" in path_lower:
        return False
    if len(content) < MIN_CHARS or len(content) > MAX_CHARS:
        return False
    lines = content.splitlines()
    if len(lines) < MIN_LINES:
        return False
    if max((len(l) for l in lines), default=0) > MAX_LINE_LENGTH:
        return False
    avg_ll = sum(len(l) for l in lines) / max(len(lines), 1)
    if avg_ll > MAX_AVG_LINE_LENGTH:
        return False
    alphanum = sum(c.isalnum() for c in content)
    if alphanum / max(len(content), 1) < MIN_ALPHANUM_RATIO:
        return False
    comment_lines = sum(
        1 for l in lines
        if l.strip().startswith("//") or l.strip().startswith("*")
    )
    if comment_lines / max(len(lines), 1) > MAX_COMMENT_RATIO:
        return False
    header = "\n".join(lines[:20])
    if AUTOGEN_RE.search(header):
        return False
    return True


def has_modern_csharp(content: str) -> bool:
    return bool(MODERN_RE.search(content))


def has_ci_workflows(repo) -> bool:
    """Check if the repo has GitHub Actions workflows."""
    try:
        contents = repo.get_contents(".github/workflows")
        return len(contents) > 0
    except GithubException:
        return False


def has_test_files(repo) -> bool:
    """Search for test files in the repo."""
    try:
        results = repo.get_contents("")  # root listing
        for item in results:
            name_lower = item.name.lower()
            if any(t in name_lower for t in ["test", "spec", "xunit", "nunit", "mstest"]):
                return True
    except GithubException:
        pass
    # Also try searching for test patterns in file names
    try:
        code = repo.get_git_tree("HEAD", recursive=True)
        for element in code.tree[:500]:  # limit to first 500 entries
            if element.type == "blob" and element.path.endswith(".cs"):
                if any(t in element.path.lower() for t in ["test", "spec"]):
                    return True
    except GithubException:
        pass
    return False


def fetch_cs_files(repo, token: str, max_files: int) -> list[dict]:
    """Fetch all .cs files from a repo using the git tree API."""
    files = []
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3.raw",
    }

    try:
        tree = repo.get_git_tree("HEAD", recursive=True)
    except GithubException:
        return files

    cs_paths = [
        el.path for el in tree.tree
        if el.type == "blob" and el.path.endswith(".cs")
    ][:max_files]

    for path in cs_paths:
        url = f"https://api.github.com/repos/{repo.full_name}/contents/{path}"
        try:
            resp = requests.get(url, headers=headers, timeout=15)
            if resp.status_code == 200:
                # Raw content via Accept header
                content = resp.text
                if is_quality_content(content, path):
                    files.append({
                        "content": content,
                        "path": path,
                        "repo_name": repo.full_name,
                        "stars": repo.stargazers_count,
                        "license": repo.license.spdx_id if repo.license else "unknown",
                        "modern_csharp": has_modern_csharp(content),
                        "source": "github-scraped",
                    })
            elif resp.status_code == 403:
                time.sleep(60)  # rate limited on raw content
        except requests.RequestException:
            continue
        time.sleep(0.05)  # be a good citizen

    return files


def wait_for_rate_limit(g: Github):
    # PyGithub v2+ removed .core from RateLimitOverview
    # Just sleep between API calls instead of checking rate limits
    pass


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output_dir", default="./data/github_csharp")
    parser.add_argument("--max_repos", type=int, default=MAX_REPOS)
    parser.add_argument("--require_ci", action="store_true", default=True,
                        help="Only include repos with GitHub Actions CI")
    parser.add_argument("--require_tests", action="store_true", default=True,
                        help="Only include repos with test files")
    parser.add_argument("--modern_only", action="store_true", default=False,
                        help="Only include files with modern C# features")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN environment variable is required")

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    g = Github(auth=Token(token))
    seen_repos = set()
    total_files = 0
    shard_idx = 0
    shard_records = []
    SHARD_SIZE = 20_000

    def flush_shard():
        nonlocal shard_idx
        shard_path = out_dir / f"shard_{shard_idx:04d}.jsonl"
        with open(shard_path, "w", encoding="utf-8") as f:
            for rec in shard_records:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
        print(f"  → Wrote shard {shard_idx} ({len(shard_records)} records)")
        shard_idx += 1
        shard_records.clear()

    for query in REPO_SEARCH_QUERIES:
        print(f"\nSearching: {query}")

        try:
            results = g.search_repositories(
                query=query,
                sort="stars",
                order="desc"
            )
        except RateLimitExceededException:
            # In v2+, RateLimitExceededException may not be raised
            # Rate limit errors come as GithubException with status 403
            print("  Rate limit exceeded, waiting 60s...")
            time.sleep(60)
            continue

        repo_bar = tqdm(results, desc="Repos", unit=" repos")
        for repo in repo_bar:
            if repo.full_name in seen_repos:
                continue
            if len(seen_repos) >= args.max_repos:
                break
            seen_repos.add(repo.full_name)

            # Quality gate on the repo itself
            try:
                langs = repo.get_languages()
                total_bytes = sum(langs.values()) or 1
                csharp_ratio = langs.get("C#", 0) / total_bytes
                if csharp_ratio < MIN_CSHARP_RATIO:
                    continue
                if args.require_ci and not has_ci_workflows(repo):
                    continue
                if args.require_tests and not has_test_files(repo):
                    continue
            except GithubException:
                continue

            # Fetch files
            files = fetch_cs_files(repo, token, MAX_FILES_PER_REPO)

            if args.modern_only:
                files = [f for f in files if f["modern_csharp"]]

            shard_records.extend(files)
            total_files += len(files)
            repo_bar.set_postfix(files=total_files, repos=len(seen_repos))

            if len(shard_records) >= SHARD_SIZE:
                flush_shard()

    if shard_records:
        flush_shard()

    print(f"\nDone. Scraped {total_files:,} files from {len(seen_repos):,} repos.")
    print(f"Output: {out_dir}")


if __name__ == "__main__":
    main()

